export const types = {

	USER_UPDATE  : 'USER_UPDATE' ,
  USER_RESET : 'USER_RESET',
  USER_SETTINGS_UPDATE_LANGUAGE : 'USER_SETTINGS_UPDATE_LANGUAGE',
  POSTS_UPDATE_LIST : 'POSTS_UPDATE_LIST',
  POSTS_GET_LIST : 'POSTS_GET_LIST',

}
